version: 2.0
jobs:
    build:
        machine:
            image: ubuntu-1604:202007-01
        steps:
            - checkout
            - run:
                name: Build
                command: |
                    mkdir build
                    cd build
                    cmake ..
                    cmake --build .
            - run:
                name: Test
                command: |
                    echo "Test"
