version: 2.0
jobs:
    build:
        docker:
            - image: cimg/base:2020.01
        steps:
            - checkout
            - run:
                name: Install GCC
                command: 'sudo apt-get update && sudo apt-get install -y gcc g++'
            - run:
                name: Install CMake
                command: | 
                    version=3.13
                    build=4
                    mkdir ~/temp
                    cd ~/temp
                    wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
                    tar -xzvf cmake-$version.$build.tar.gz
                    cd cmake-$version.$build/
                    ./bootstrap
                    make -j$(nproc)
                    sudo make install
            - run:
                name: Build
                command: |
                    mkdir build
                    cd build
                    cmake ..
                    cmake --build .
            - run:
                name: Test
                command: |
                    echo "Test"
