version: 2.0
jobs:
    build:
        docker:
            - image: cimg/base:2020.01
        steps:
            - checkout
            - run:
                name: Install GCC
                command: 'sudo apt-get update && sudo apt-get install -y gcc g++'
            - run:
                name: Install CMake
                command: 'sudo apt-get update && sudo apt-get install -y cmake' 
            - run:
                name: Build
                command: |
                    mkdir build
                    cd build
                    cmake ..
                    cmake --build .
            - run:
                name: Test
                command: |
                    echo "Test"
