version: 2.0
jobs:
    build:
        docker:
            - image: cimg/base:2020.01
        steps:
            - checkout
            - run:
                name: Install Deps
                command: |
                    cd scripts
                    chmod +x install_dependencies
                    sudo ./install_dependencies
            - run:
                name: Build
                command: |
                    mkdir build
                    cd build
                    cmake ..
                    cmake --build .
            - run:
                name: Test
                command: |
                    echo "Test"
