version: 2.0
jobs:
    build:
        machine:
            image: cimg/base:2020.01
        steps:
            - checkout
            - run:
                name: Update
                command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
            - run:
                name: Install GCC
                command: 'apt-get update && sudo apt-get install -y gcc g++'
            - run:
                name: Install CMake
                command: 'apt-get update && sudo apt-get install -y cmake' 
            - run:
                name: Build
                command: |
                    mkdir build
                    cd build
                    cmake ..
                    cmake --build .
            - run:
                name: Test
                command: |
                    echo "Test"
