version: 2.1

jobs:
    build:
        docker:
            - image: cimg/base:2020.01
        steps:
            - checkout
            - run:
                name: Dependencies
                command: |
                    cd scripts
                    chmod +x install.bash
                    sudo ./install.bash
            - run:
                name: Build
                command: |
                    cmake -H. -Bbuild
                    cmake --build build
            - run:
                name: Test
                command: |
                    echo "Test"